services:
  location-service:
    build:
      context: .
      dockerfile: ./location-service/Dockerfile
    container_name: weather-location-service
    environment:
      - LOCATION_PORT=${LOCATION_SERVICE_PORT}
    ports:
      - "${LOCATION_SERVICE_PORT}:50051"
    volumes:
      - ./proto:/app/proto:ro

  weather-service:
    build:
      context: .
      dockerfile: ./weather-service/DockerFile
    container_name: weather-weather-service
    environment:
      - WEATHER_PORT=${WEATHER_SERVICE_PORT}
    ports:
      - "${WEATHER_SERVICE_PORT}:50052"
    volumes:
      - ./proto:/app/proto:ro

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    environment:
      - GATEWAY_PORT=${GATEWAY_PORT:-3000}
      - LOCATION_SERVICE_HOST=${LOCATION_SERVICE_HOST:-location-service}
      - LOCATION_SERVICE_PORT=${LOCATION_SERVICE_PORT:-50051}
      - WEATHER_SERVICE_HOST=${WEATHER_SERVICE_HOST:-weather-service}
      - WEATHER_SERVICE_PORT=${WEATHER_SERVICE_PORT:-50052}
      - PROTO_PATH=/app/proto/weatherapp.proto
    volumes:
      - ./proto:/app/proto:ro
    ports:
      - "3000:3000"
    depends_on:
      - location-service
      - weather-service

