FROM python:3.11-slim
WORKDIR /app

COPY weather-service/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY weather-service/ ./

ENV PYTHONPATH=/app:/app/proto
ENV WEATHER_PORT=50052
EXPOSE 50052

CMD ["python", "WeatherService.py"]
