# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: weatherapp.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'weatherapp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10weatherapp.proto\x12\nweatherapp\"$\n\x16LocationServiceRequest\x12\n\n\x02ip\x18\x01 \x01(\t\"/\n\x13LocationCoordinates\x12\x0b\n\x03lat\x18\x01 \x01(\x01\x12\x0b\n\x03lon\x18\x02 \x01(\x01\"\xb1\x01\n\x16WeatherServiceResponse\x12\x13\n\x0btemperature\x18\x01 \x01(\x01\x12\x11\n\twindspeed\x18\x02 \x01(\x01\x12\x18\n\x10observation_time\x18\x03 \x01(\t\x12\x18\n\x10unit_temperature\x18\x04 \x01(\t\x12\x16\n\x0eunit_windspeed\x18\x05 \x01(\t\x12\x10\n\x08humidity\x18\x06 \x01(\x01\x12\x11\n\tprecip_mm\x18\x07 \x01(\x01\x32\x65\n\x0fLocationService\x12R\n\x0bgetLocation\x12\".weatherapp.LocationServiceRequest\x1a\x1f.weatherapp.LocationCoordinates2c\n\x0eWeatherService\x12Q\n\nGetWeather\x12\x1f.weatherapp.LocationCoordinates\x1a\".weatherapp.WeatherServiceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'weatherapp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOCATIONSERVICEREQUEST']._serialized_start=32
  _globals['_LOCATIONSERVICEREQUEST']._serialized_end=68
  _globals['_LOCATIONCOORDINATES']._serialized_start=70
  _globals['_LOCATIONCOORDINATES']._serialized_end=117
  _globals['_WEATHERSERVICERESPONSE']._serialized_start=120
  _globals['_WEATHERSERVICERESPONSE']._serialized_end=297
  _globals['_LOCATIONSERVICE']._serialized_start=299
  _globals['_LOCATIONSERVICE']._serialized_end=400
  _globals['_WEATHERSERVICE']._serialized_start=402
  _globals['_WEATHERSERVICE']._serialized_end=501
# @@protoc_insertion_point(module_scope)
